version: '3.8'

services:
  mariadb:
    container_name: aio_mariadb
    image: bitnami/mariadb:11.2.3-debian-12-r4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/bitnami/maria
    restart: always
    networks:
      - mariadb_network

  phpmyadmin:
    image: bitnami/phpmyadmin:5.2.1-debian-12-r20
    container_name: aio_pma
    ports:
      - "8081:8080"
    depends_on:
      - mariadb
    restart: always
    networks:
      - mariadb_network

  tomcat:
    container_name: aio_tomcat
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - ./target:/usr/local/tomcat/webapps
    restart: always
    networks:
      - mariadb_network

volumes:
  mariadb_data:
    driver: local

networks:
  mariadb_network:
    driver: bridge